Add the header file
KristerJazz/P1.9_Collaborative_Project pull request #4
Opened 2020-02-12 17:38 UTC by stefanocampanella

2020-02-12 17:58 UTC, lleon95 commented on include/ljmd.h
> + * latest revision: Stefano Campanella, 02/12/2020
By experience, adding the latest version is kind of useless. You can forget updating it.

2020-02-12 17:58 UTC, lleon95 commented on include/ljmd.h
> +static int get_a_line(FILE *fp, char *buf);
Remove static keyword

2020-02-12 17:58 UTC, lleon95 commented on include/ljmd.h
> +static void azzero(double *d, const int n);
Remove static keyword

2020-02-12 17:58 UTC, lleon95 commented on include/ljmd.h
> +static double pbc(double x, const double boxby2);
Remove static keyword

2020-02-12 17:58 UTC, lleon95 commented on include/ljmd.h
> +static void ekin(mdsys_t *sys);
Remove static keyword

2020-02-12 17:58 UTC, lleon95 commented on include/ljmd.h
> +static void force(mdsys_t *sys);
Remove static keyword

2020-02-12 17:58 UTC, lleon95 commented on include/ljmd.h
> +static void velverlet(mdsys_t *sys);
Remove static keyword

2020-02-12 17:58 UTC, lleon95 commented on include/ljmd.h
> +static void output(mdsys_t *sys, FILE *erg, FILE *traj);
Remove static keyword

2020-02-12 17:59 UTC, lleon95 requested changes

2020-02-12 17:59 UTC, lleon95 commented on include/ljmd.h
> +int get_a_line(FILE *fp, char *buf);
Add <stdio.h>

2020-02-12 18:04 UTC, lleon95 requested changes

2020-02-12 18:04 UTC, lleon95 commented on include/ljmd.h
> +#include <stdio.h>
It is outside of the header guard

2020-02-12 18:06 UTC, lleon95 approved these changes

2020-02-12 20:59 UTC, lleon95 requested changes

2020-02-12 20:59 UTC, lleon95 commented on include/ljmd.h
> +const double kboltz = 0.0019872067;
This constant will lead to conflicts when linking. Please, do:

1. Use: 

```c
extern const double kboltz;
extern const double mvsq2e;
```

2. Create a file named: "constants.c" with the following contents:

```c
#include "../include/ljmd.h"

const double kboltz = 0.0019872067;
const double mvsq2e = 2390.05736153349;
```

2020-02-13 08:53 UTC, lleon95 approved these changes

2020-02-13 10:27 UTC, mattiacmhpc approved these changes

2020-02-13 10:30 UTC, merged