Mattiacmhpc utilities
KristerJazz/P1.9_Collaborative_Project pull request #5
Opened 2020-02-12 17:42 UTC by mattiacmhpc

I add into /src/ utilities.c file which contains utilities functions and I add the #include needed as Stefano request

2020-02-12 17:52 UTC, lleon95 requested changes

2020-02-12 17:52 UTC, lleon95 commented on src/utilities.c
> +static double pbc(double x, const double boxby2) {
Remove static keyword

2020-02-12 17:52 UTC, lleon95 commented on src/utilities.c
> +static void azzero(double *d, const int n) {
Remove static keyword

2020-02-12 17:52 UTC, lleon95 commented on src/utilities.c
> +static int get_a_line(FILE *fp, char *buf) {
Remove static keyword

2020-02-12 17:52 UTC, lleon95 commented on src/utilities.c
> +A #include<stdio.h>
Please, check this typo.

2020-02-12 17:52 UTC, lleon95 commented on src/utilities.c
> +    static int get_a_line(FILE *fp, char *buf) {
check indentation. Run: `clang-format -i --style=google`

Remove the static keyword

2020-02-12 18:01 UTC, lleon95 requested changes

2020-02-12 18:01 UTC, lleon95 commented on src/utilities.c
>  #include <string.h>
Project's header is missing. Ask @stefanocampanella  for it

2020-02-12 18:05 UTC, lleon95 approved these changes

2020-02-12 20:50 UTC, lleon95 requested changes

2020-02-12 20:50 UTC, lleon95 commented on src/utilities.c
> +#include "../include/ljmod.h"
Typo: 

#include "../include/ljmd.h"

2020-02-12 21:00 UTC, lleon95 requested changes

2020-02-12 21:00 UTC, lleon95 commented on src/utilities.c
> +int get_a_line(FILE *fp, char *buf) {
Delete this function, since it is for INPUT purposes

2020-02-13 10:27 UTC, stefanocampanella approved these changes

2020-02-13 10:30 UTC, lleon95 approved these changes

2020-02-13 10:32 UTC, merged